# -*- coding: utf-8 -*-
"""BIG 5 personality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4QGnlBcu1kyJSOiFqLGbsuJY6T50xn_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

import pandas as pd
df = pd.read_csv("data-final.csv", sep="\t")
df.head()

#delete the last columns except country
df.columns[-10:]

df.drop(df.columns[-10:-3], axis = 1, inplace = True)
df.drop(df.columns[-2:], axis = 1, inplace = True)
df.head(3)

df_e = df.iloc[:, 50:-1]
df.drop(df.columns[50:-1], axis = 1, inplace = True)
df_e.head()

df = df.replace(0, 1)

data_copy = df
data_copy

#let's see the null values

df.isnull().sum()

#Number of participants after eliminating null values

print("Total number of participants: ", len(df))
print("Total number of participants with missing values: ", len(df)-len(df.dropna(inplace=False)))

print("\nNumber of countries: ", len(df['country'].unique()))
print("Number of countries with +5000 participants: ", len(df['country'].value_counts()[lambda x: x > 5000]))

#deleting the missing values as it doesn't affect anything
df.dropna(inplace = True)

plt.figure(figsize=(6,4))
df["country"].value_counts()[lambda x: x > 5000].plot(kind='bar')
plt.title("")
plt.xlabel("Country")
plt.ylabel("Number of Participants")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Questions

# Extroversion is a personality trait typically characterized by outgoingness, high energy, and/or talkativeness.
ext_questions = {'EXT1' : 'I am the life of the party', # + point
                 'EXT2' : 'I dont talk a lot', # - point
                 'EXT3' : 'I feel comfortable around people', # +
                 'EXT4' : 'I keep in the background', # -
                 'EXT5' : 'I start conversations', # +
                 'EXT6' : 'I have little to say', # -
                 'EXT7' : 'I talk to a lot of different people at parties', # +
                 'EXT8' : 'I dont like to draw attention to myself', # -
                 'EXT9' : 'I dont mind being the center of attention', # +
                 'EXT10': 'I am quiet around strangers'} # -
#Positive points: 1 3 5 7 9
#Negative points: 2 4 6 8 10


# Neuroticism, one of the Big 5 personality traits, is typically defined as a tendency toward anxiety, depression,
# self-doubt, and other negative feelings
est_questions = {'EST1' : 'I get stressed out easily', #+
                 'EST2' : 'I am relaxed most of the time', #-
                 'EST3' : 'I worry about things', #+
                 'EST4' : 'I seldom feel blue', #-
                 'EST5' : 'I am easily disturbed', #+
                 'EST6' : 'I get upset easily', #+
                 'EST7' : 'I change my mood a lot',#+
                 'EST8' : 'I have frequent mood swings',#+
                 'EST9' : 'I get irritated easily',#+
                 'EST10': 'I often feel blue'} #+
#Positive points: 1 3 5 6 7 8 9 10
#Negative points: 2 4


# Agreeableness is a personality trait that can be described as cooperative, polite, kind, and friendly.
agr_questions = {'AGR1' : 'I feel little concern for others', #-
                 'AGR2' : 'I am interested in people', #+
                 'AGR3' : 'I insult people', #-
                 'AGR4' : 'I sympathize with others feelings', #+
                 'AGR5' : 'I am not interested in other peoples problems', #-
                 'AGR6' : 'I have a soft heart', #+
                 'AGR7' : 'I am not really interested in others', #-
                 'AGR8' : 'I take time out for others', #+
                 'AGR9' : 'I feel others emotions', #+
                 'AGR10': 'I make people feel at ease'} #+
#Positive points: 2 4 6 8 9 10
#Negative points: 1 3 5 7


# Conscientiousness is a fundamental personality trait—one of the Big Five—that reflects the tendency to be responsible, organized,
# hard-working, goal-directed, and to adhere to norms and rules.
csn_questions = {'CSN1' : 'I am always prepared', #+
                 'CSN2' : 'I leave my belongings around', #-
                 'CSN3' : 'I pay attention to details', #+
                 'CSN4' : 'I make a mess of things', #-
                 'CSN5' : 'I get chores done right away', #+
                 'CSN6' : 'I often forget to put things back in their proper place', #-
                 'CSN7' : 'I like order', #+
                 'CSN8' : 'I shirk my duties', #-
                 'CSN9' : 'I follow a schedule', #+
                 'CSN10' : 'I am exacting in my work'#+
                }
#Positive points: 1 3 5 7 9 10
#Negative points: 2 4 6 8


# Openness to experience, or simply openness, is a basic personality trait denoting receptivity to new ideas and new experiences.

opn_questions = {'OPN1' : 'I have a rich vocabulary', #+
                 'OPN2' : 'I have difficulty understanding abstract ideas', #-
                 'OPN3' : 'I have a vivid imagination', #+
                 'OPN4' : 'I am not interested in abstract ideas', #-
                 'OPN5' : 'I have excellent ideas', #+
                 'OPN6' : 'I do not have a good imagination', #+
                 'OPN7' : 'I am quick to understand things', #+
                 'OPN8' : 'I use difficult words', #+
                 'OPN9' : 'I spend time reflecting on things', #+
                 'OPN10': 'I am full of ideas'} #+
#Positive points: 1 3 5 6 7 8 9 10
#Negative points: 2 4


# Group Names and Columns
EXT = [column for column in df if column.startswith('EXT')]
EST = [column for column in df if column.startswith('EST')]
AGR = [column for column in df if column.startswith('AGR')]
CSN = [column for column in df if column.startswith('CSN')]
OPN = [column for column in df if column.startswith('OPN')]

# function to visualize the questions and answers distribution
def vis_questions(groupname, questions):
    plt.figure(figsize=(40,60))
    for i in range(1, 11):
        plt.subplot(10,5,i)
        plt.hist(df[groupname[i-1]], bins=14, color= 'orange', alpha=.5)
        plt.title(questions[groupname[i-1]], fontsize=18)

vis_questions(EXT, ext_questions)
vis_questions(EST, est_questions)
vis_questions(AGR, agr_questions)
vis_questions(CSN, csn_questions)
vis_questions(OPN, opn_questions)

df.describe().T

#classifying +ve and -ve scores in questions

ext_positives = ['EXT1','EXT3','EXT5','EXT7','EXT9']
ext_negatives = ['EXT2', 'EXT4', 'EXT6', 'EXT8', 'EXT10']

est_positives = ['EST1','EST3','EST5','EST6','EST7','EST8','EST9','EST10']
est_negatives = ['EST2','EST4']

agr_positives =['AGR2','AGR4','AGR6','AGR8','AGR9','AGR10']
agr_negatives =['AGR1','AGR3','AGR5','AGR7']

csn_positives = ['CSN1','CSN3','CSN5','CSN7','CSN9','CSN10']
csn_negatives = ['CSN2','CSN4','CSN6','CSN8']

opn_positives = ['OPN1','OPN3','OPN5','OPN6','OPN7','OPN8','OPN9','OPN10']
opn_negatives = ['OPN2','OPN4']

def reverse_items(columns, max_scale=5):

    """
    Reverses the Likert scores in the specified columns.

    columns: list of columns to be reversed
    max_scale: Maximum value of the Likert scale
    """

    for col in columns:
        df[col] = (max_scale + 1) - df[col]

def scoreCalculator(group,groupname=""):
    df[f"{groupname}_Score"] = df[group].mean(axis=1)

reverse_items(ext_negatives)
reverse_items(est_negatives)
reverse_items(agr_negatives)
reverse_items(csn_negatives)
reverse_items(opn_negatives)

scoreCalculator(EXT,"Extroversion")
scoreCalculator(EST,"Neuroticism")
scoreCalculator(AGR,"Agreeableness")
scoreCalculator(CSN,"Conscientiousness")
scoreCalculator(OPN,"Openness")

from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from yellowbrick.cluster import KElbowVisualizer

scores_df = df.iloc[:, -5:]
columns = list(scores_df.columns)

scaler = MinMaxScaler(feature_range=(0,1))
scores_df = scaler.fit_transform(scores_df)
scores_df = pd.DataFrame(scores_df, columns = columns)

scores_df['country'] = df['country']
scores_df

#Note that 0.5 is mid point, 1 is max point and 0 is min point
#For example if a participant's ext_point = 0.5 then they are neither extrovert nor introvert for, they are right in the middle

#Let's look at the average scores of the 10 most populous countries & save them for later
country_scores = scores_df.groupby("country").mean().loc[scores_df['country'].value_counts().head(10).index]
country_scores

country_scores.plot(kind="bar", figsize=(14,6))
plt.title("Country Scores")
plt.ylabel("Score")
plt.xlabel("Country")
plt.legend(title="Score Type")
plt.ylim(0,1)
plt.yticks(np.arange(0, 1.1, 0.1))
plt.tight_layout()
plt.show()

#Let's look the average values of all people

scores_df.drop('country',axis=1).mean().to_frame(name = "mean")

#For example: 0.5 is normal, 0 is fully introvert, 1 is fully extrovert

#Let's remember df
df.head()

#We don't need last 6 columns for clustering and we've already saved them to scores_df
df.drop(df.columns[-6:], axis = 1, inplace = True)
df.head()

df_model = data_copy[:5000] #I will use df_model to training processes

kmeans = KMeans()
visualizer = KElbowVisualizer(kmeans, k=(2,10))
visualizer.fit(df_model)
visualizer.poof()

df_model = data_copy

kmeans = KMeans(n_clusters=5)
k_fit = kmeans.fit(df_model)

k_fitted = k_fit.labels_
df_model['Clusters'] = k_fitted
df_model.head()

df_model.Clusters.value_counts()

scores_df['Clusters'] = k_fitted
scores_df.drop('country',axis=1).groupby('Clusters').mean()

dataclusters = scores_df.drop('country',axis=1).groupby('Clusters').mean()
plt.figure(figsize=(22,3))
for i in range(0, 5):
    plt.subplot(1,5,i+1)
    plt.bar(dataclusters.columns, dataclusters.iloc[:, i], color='blue', alpha=0.2)
    plt.plot(dataclusters.columns, dataclusters.iloc[:, i], color='black')
    plt.title('Cluster ' + str(i))
    plt.xticks(rotation=45)
    plt.ylim(0,1);

#Using PCA to visualize Clusters in 2D Graph
pca = PCA(n_components=2)
pca_fit = pca.fit_transform(df_model)

df_pca = pd.DataFrame(data=pca_fit, columns=['PCA1', 'PCA2'])
df_pca['Clusters'] = k_fitted

plt.figure(figsize=(10,10))
sns.scatterplot(data=df_pca, x='PCA1', y='PCA2', hue='Clusters', palette='Set2', alpha=0.8)
plt.title('Personality Clusters after PCA');

scores_df['Clusters'] = k_fitted
country_clusters = scores_df.groupby(['country', 'Clusters']).size().reset_index(name='Count')
country_clusters.head()

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# single PCA space for all participants
pca = PCA(n_components=2, random_state=42)
Z = pca.fit_transform(df_model)          # df_model = scaled 5 trait columns (no country)
df_pca = pd.DataFrame(Z, columns=["PCA1","PCA2"])
df_pca["Cluster"] = k_fitted             # KMeans labels
df_pca["country"] = scores_df["country"] # attach country

# limit to top N countries and sample to reduce overplotting
topN = 8
top_countries = df_pca["country"].value_counts().head(topN).index
small = (df_pca[df_pca["country"].isin(top_countries)]
         .groupby("country", group_keys=False)
         .apply(lambda g: g.sample(min(len(g), 3000), random_state=42)))  # ≤3k pts per country

# ompute cluster centroids per country to overlay
centroids = (small.groupby(["country","Cluster"])[["PCA1","PCA2"]]
             .mean().reset_index())

# one panel per country
g = sns.relplot(
    data=small, x="PCA1", y="PCA2", hue="Cluster",
    col="country", col_wrap=4, kind="scatter",
    height=3.5, aspect=1, alpha=0.6, s=10, palette="Set2",
    facet_kws=dict(sharex=True, sharey=True)
)
g.set_titles("{col_name}")
g.set_axis_labels("PCA1", "PCA2")
g._legend.set_title("Clusters")

# Overlay centroids as big markers (✕)
for ax, country in zip(g.axes.flat, g.col_names):
    cc = centroids[centroids["country"] == country]
    ax.scatter(cc["PCA1"], cc["PCA2"], s=160, marker="X", linewidths=1.2, edgecolors="black", alpha=0.9)

plt.suptitle("Personality Clusters after PCA — per Country", y=1.02, fontsize=14)
plt.tight_layout()
plt.show()

country_stats = (
    scores_df
    .groupby('country')
    .agg({
        'Extroversion_Score': 'mean',
        'Neuroticism_Score': 'mean',
        'Agreeableness_Score': 'mean',
        'Conscientiousness_Score': 'mean',
        'Openness_Score': 'mean',
        'country': 'count'   # count participants
    })
    .rename(columns={'country': 'Participants'})
    .reset_index()
)
country_stats.head()

traits = [
    'Extroversion_Score',
    'Neuroticism_Score',
    'Agreeableness_Score',
    'Conscientiousness_Score',
    'Openness_Score'
]
country_stats = country_stats[country_stats['Participants'] >= 50]
highest = []
for trait in traits:
    idx = country_stats[trait].idxmax()
    highest.append({
        'Trait': trait,
        'Country': country_stats.loc[idx, 'country'],
        'Score': round(country_stats.loc[idx, trait], 3),
        'Participants': country_stats.loc[idx, 'Participants']
    })

summary = pd.DataFrame(highest)
summary